name: app

type: "nodejs:10"

# dependencies:
#   nodejs:
#     yarn: "*"

# The size of the persistent disk of the application (in MB).
disk: 1024

# The mounts that will be performed when the package is deployed.
# mounts:
#   "/build": "shared:files/build"

hooks:
  # npm run buildenvvar
  # set -e
  build: |
    npm install
    npm run build

# The configuration of app when it is exposed to the web.
web:
  commands:
    start: node server.js
